import './globals.css';

export const metadata = {
  title: 'Dragon News',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
